Tamin/Controllers/AdminHomeController.cs
using System.Web.Mvc;

namespace Tamin.Controllers
{
    public class AdminHomeController : Controller
    {
        [Authorize]

        // GET: AdminHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tamin/Controllers/AdminPostsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamin.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Tamin.Controllers
{
    [Authorize]

    public class AdminPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminPosts
        public async Task<ActionResult> Index()
        {
            var posts = db.Posts.Include(p => p.ApplicationUser).Include(p => p.PostGroups).OrderBy(p=>p.PostDate).ThenBy(p=>p.Modifiedat);
            return View(await posts.ToListAsync());
        }

        public ActionResult ShowByGroup(int? id)
        {
            var posts = (from p in db.Posts
                where p.PostGroupID == id
                select p);
            return View(posts.ToList());
        }


        public ActionResult Shownews()
        {
            var posts = (from p in db.Posts
                    where (p.PostIsActive && !p.Is_delete && (p.Startdate!=null  && p.Startdate <= DateTime.Now)) ||
                          (p.PostIsActive && !p.Is_delete && (p.Enddate != null && p.Enddate >= DateTime.Now)) ||
                          (p.PostIsActive && !p.Is_delete && (p.Startdate != null && p.Startdate <= DateTime.Now) && (p.Enddate != null && p.Enddate >= DateTime.Now)) ||
                          (p.PostIsActive && !p.Is_delete)
                         select p)
                .OrderByDescending(x => x.Priority)
                .ThenByDescending(y => y.PostID);

            return View(posts.ToList());
        }
        
        // GET: AdminPosts/Details/5
        public async Task<ActionResult> PostDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: AdminPosts/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Fullname");
            ViewBag.PostGroupID = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle");
            return View();
        }

        // POST: AdminPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PostID,PostGroupID,ApplicationUserId,PostTitle,Summary,PostText,PostIsActive,PostDate,Modifiedat,Modifiedby,Is_delete,Startdate,Enddate,Comment_conut,Comment_status,ImageUrl,PostThumbnailImageUrl,Priority")] Post post, HttpPostedFileBase ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null)
                {
                    string filename = Path.GetFileName(ImageUrl.FileName);
                    string newFilename = Guid.NewGuid().ToString()
                                             .Replace("-", string.Empty) +
                                         Path.GetExtension(filename);
                    var newFilenameUrl = "/Uploads/Post/" + newFilename;
                    string physicalFilename = Server.MapPath(newFilenameUrl);
                    ImageUrl.SaveAs(physicalFilename);
                    var thumbnailUrl = Utils.CreateThumbnail(physicalFilename);
                    post.ImageUrl = newFilenameUrl;
                    post.PostThumbnailImageUrl = thumbnailUrl;
                }
                post.ApplicationUserId = User.Identity.GetUserId();
                post.PostText = Server.HtmlDecode(post.PostText);
                post.PostDate=DateTime.Now.AddDays(1);
                db.Posts.Add(post);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Fullname", post.ApplicationUserId);
            ViewBag.PostGroupID = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle", post.PostGroupID);
            return View(post);
        }

        // GET: AdminPosts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Fullname", post.ApplicationUserId);
            ViewBag.PostGroupID = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle", post.PostGroupID);
            return View(post);
        }

        // POST: AdminPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PostID,PostGroupID,ApplicationUserId,PostTitle,Summary,PostText,PostIsActive,Modifiedat,Modifiedby,Is_delete,Startdate,Enddate,Comment_conut,Comment_status,ImageUrl,PostThumbnailImageUrl,Priority")] Post post, HttpPostedFileBase ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null)
                {
                    string filename = Path.GetFileName(ImageUrl.FileName);
                    string newFilename = Guid.NewGuid().ToString().Replace("-", string.Empty)
                                         + Path.GetExtension(filename);

                    var newFilenameUrl = "/Uploads/Post/" + newFilename;
                    string physicalFilename = Server.MapPath(newFilenameUrl);

                    ImageUrl.SaveAs(physicalFilename);

                    var thumbnailUrl = Utils.CreateThumbnail(physicalFilename);

                    if (System.IO.File.Exists(Server.MapPath("~/" + post.ImageUrl)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/" + post.ImageUrl));
                    }
                    if (System.IO.File.Exists(Server.MapPath("~/" + post.PostThumbnailImageUrl)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/" + post.PostThumbnailImageUrl));
                    }
                    post.ImageUrl = newFilenameUrl;
                    post.PostThumbnailImageUrl = thumbnailUrl;
                }
                post.PostDate=DateTime.Now;
                post.Modifiedby = User.Identity.GetUserId();
                post.Modifiedat=DateTime.Now;
                post.PostText = Server.HtmlDecode(post.PostText);
                db.Entry(post).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Fullname", post.ApplicationUserId);
            ViewBag.PostGroupID = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle", post.PostGroupID);
            return View(post);
        }

        [HttpPost]
        public ActionResult Changestatus(int? id)
        {
            var original = db.Posts.Find(id);
            if (original != null)
            {
                original.PostIsActive = !original.PostIsActive;
                db.SaveChanges();
                return Content("true");
            }
            return Content("false");
        }

        // GET: AdminPosts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: AdminPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Post post = await db.Posts.FindAsync(id);
            if (post != null) db.Posts.Remove(post);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamin/Views/Shared/_LastNews.cshtml
@using Tamin.Models

@{
    var db = new ApplicationDbContext();
}

<div class="art-layout-cell art-sidebar1">
    <div class="art-block clearfix"style="float: right;">
    
        <div class="tab-content">
            <div id="latest" class="tab-pane fade in active">
                <h4 class="t active">آخرین خبرها</h4>
                <div class="art-blockcontent">
                    <ul>
                        @foreach (var item in db.Posts.Where(x => x.PostIsActive && !x.Is_delete && x.Startdate <= DateTime.Now || x.Startdate == null && x.Enddate >= DateTime.Now || x.Enddate == null)
                    .OrderByDescending(x => x.PostID).Take(5))
                        {
                            <li>
                                <a style="color: #337ab7;" href="@Url.Action("PostDetails", "Home", new {id = item.PostID}, null)">@item.PostTitle</a>
                            </li>
                        }
                    </ul>
                </div>            
            </div>

            <div id="topview" class="tab-pane fade in active">
                        <h4 class="t active">پربیننده ترین ها</h4>
                <div class="art-blockcontent">
                    <ul>
                        @foreach (var item in db.Posts.Where(x => x.PostIsActive && !x.Is_delete && x.Startdate <= DateTime.Now || x.Startdate == null && x.Enddate >= DateTime.Now || x.Enddate == null)
                    .OrderByDescending(x => x.PageCounter).Take(5))
                        {
                            <li>
                                <a style="color: #337ab7;" href="@Url.Action("PostDetails", "Home", new {id = item.PostID}, null)">@item.PostTitle</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div> 

Tamin/Views/Shared/_LayoutAdmin - Copy.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/AdminContent/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/css_woff/style.css" rel="stylesheet" />
</head>
<body>
    <div class="k-rtl">
        <section id="container">
            <!--header start-->
            <header class="header fixed-top clearfix">
                <!--logo start-->
                <div class="brand">
                    <a href="#" class="logo">
                        بخش مدیریت سایت
                    </a>
                    <div class="sidebar-toggle-box">
                        <div id="MenuRight" class="fa fa-bars"></div>
                    </div>
                </div>
                <!--logo end-->


            </header>
            <!--header end-->
            <aside>
                <div id="sidebar" class="nav-collapse">
                    <!-- sidebar menu start-->
                    <div class="leftside-navigation">
                        <ul class="sidebar-menu" id="nav-accordion">
                            <li>
                                <a class="active" href="@Url.Action("Index","AdminHome")">
                                    <i class="fa fa-dashboard"></i>
                                    <span>داشبورد</span>
                                </a>
                            </li>
                            <li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-laptop"></i>
                                    <span>بخش مدیریت</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="@Url.Action("Index","AdminUsers")"><i class="fa fa-users"></i>
                                        <span>مدیریت کاربری</span></a></li>
                                    <li><a href="@Url.Action("Index","AdminRoles")"><i class="fa fa-lock"></i>
                                        <span>مدیریت نقش ها</span></a></li>
                                    <li><a href="@Url.Action("Index","AdminComments")"><i class="fa fa-comment"></i>
                                        <span>کامنت ها</span></a></li>
                                    <li><a href="@Url.Action("Index","AdminPostGroups")"><i class="fa fa-tag"></i>
                                        <span>مجموعه ها</span></a></li>
                                    <li><a href="@Url.Action("Index","AdminPosts")"><i class="fa fa-file-text"></i>
                                        <span>مدیریت مطالب</span></a></li>
                                    <li><a href="@Url.Action("Index","AdminContacts")"><i class="fa fa-phone"></i>
                                        <span>تماس با ما</span></a></li>

                                    
                                    
                                </ul>
                            </li>



                        </ul>
                    </div>
                    <!-- sidebar menu end-->
                </div>
            </aside>
            <section id="main-content">
                <section class="wrapper">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </section>

            </section>
        </section>
    </div>
    @Scripts.Render("~/bundles/tamin")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            EditableTable.init();
            $("form").addClass("form-horizontal").attr("role", "form");
            $("#buttons * *").addClass("btn btn-primary");
            $('input[type="text"],input[type="datetime"],input[type="password"],textarea,select').addClass("form-control");
        });
    </script>
</body>
</html>

Tamin/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/mybootstrap")
    @Styles.Render("~/bundles/mybeyond")
    <link href="~/css_woff/style.css" rel="stylesheet" />
</head>
<body>
<div class="loading-container">
    <div class="loader"></div>
</div>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="navbar-container navbar-fixed-top">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">
                    <small>
                        <img src="~/assets/img/logo-inverted.png" alt="" />
                    </small>
                </a>
            </div>
            <div class="sidebar-collapse" id="sidebar-collapse">
                <i class="collapse-icon fa fa-bars"></i>
            </div>
            <div class="navbar-header pull-left">
                <div class="navbar-account">
                    <ul class="account-area">
                        <li>
                            <a class="login-area dropdown-toggle" data-toggle="dropdown">
                                <div class="avatar" title="View your public profile">
                                    <img src="~/assets/img/avatars/useravatar.jpg">
                                </div>
                                <section>
                                    <h2>
                                        <span class="profile">
                                            @{
                                                if (Request.IsAuthenticated)
                                                {
                                                    @User.Identity.GetUserName()
                                                }
                                            }
                                        </span>
                                    </h2>
                                </section>
                            </a>
                            <ul class="pull-right dropdown-menu dropdown-arrow dropdown-login-area">
                                <li class="username">
                                    @{
                                        if (Request.IsAuthenticated)
                                        {
                                            @User.Identity.GetUserName()
                                        }
                                    }
                                @*<li>
                                    <a href="">تغییر رمز ورود</a>
                                </li>*@
                                <li class="theme-area">
                                    <ul class="colorpicker" id="skin-changer">
                                        <li><a class="colorpick-btn" href="#" style="background-color: #5DB2FF;" rel="~/assets/css/skins/blue.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #2dc3e8;" rel="~/assets/css/skins/azure.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #03B3B2;" rel="~/assets/css/skins/teal.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #53a93f;" rel="~/assets/css/skins/green.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #FF8F32;" rel="~/assets/css/skins/orange.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #cc324b;" rel="~/assets/css/skins/pink.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #AC193D;" rel="~/assets/css/skins/darkred.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #8C0095;" rel="~/assets/css/skins/purple.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #0072C6;" rel="~/assets/css/skins/darkblue.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #585858;" rel="~/assets/css/skins/gray.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #474544;" rel="~/assets/css/skins/black.min.css"></a></li>
                                        <li><a class="colorpick-btn" href="#" style="background-color: #001940;" rel="~/assets/css/skins/deepblue.min.css"></a></li>
                                    </ul>
                                </li>
                                <li class="dropdown-footer">
                                    
                                    <a class="" href="javascript:document.getElementById('logoutForm').submit()">
                                         خروج از پرتال
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="main-container container-fluid">
    <div class="page-container">
        <div class="page-sidebar sidebar-fixed" id="sidebar">
            <div class="sidebar-header-wrapper">
                <input type="text" class="searchinput" />
                <i class="searchicon fa fa-search"></i>
            </div>
            <ul class="nav sidebar-menu">  
                <li>
                    <a href="@Url.Action("Index", "AdminHome")">
                        <i class="menu-icon fa fa-desktop"></i>
                        <span>داشبورد</span>
                    </a>
                </li>
                <li class="active open">
                    <a href="#" class="menu-dropdown">
                        <i class="menu-icon fa fa-user-secret"></i>
                        <span class="menu-text">مدیریت مطالب</span>
                        <i class="menu-expand"></i>
                    </a>
                    <ul class="submenu">
                        <li>
                            <a href="@Url.Action("Index","AdminPosts")"><i class="fa fa-file-text"></i>
                                <span>مدیریت مطالب</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","AdminPostGroups")"><i class="fa fa-tag"></i>
                                <span>مجموعه ها</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","AdminComments")"><i class="fa fa-comment"></i>
                                <span>کامنت ها</span></a>
                        </li>
                    </ul>
                </li>
                
                <li>
                    <a href="#" class="menu-dropdown">
                        <i class="menu-icon fa fa-user-secret"></i>
                        <span class="menu-text">مدیریت کاربری</span>

                        <i class="menu-expand"></i>
                    </a>
                    <ul class="submenu">
                        <li>
                            <a href="@Url.Action("Index","AdminUsers")">
                                <i class="fa fa-users"></i>
                                <span>مدیریت کاربری</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","AdminRoles")">
                                <i class="fa fa-lock"></i>
                                <span>مدیریت نقش ها</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Index", "AdminContacts")">
                        <i class="menu-icon fa fa-phone"></i>
                        <span>تماس با ما</span>
                    </a>
                </li>
            </ul>

        </div>
        <div class="page-content">
            <div class="page-breadcrumbs breadcrumbs-fixed">
                <ul class="breadcrumb">
                    <li>
                        پرتال سازمان تأمین اجتماعی شعبه شهر صنعتی رشت</li>
                </ul>
            </div>
            <div class="page-header position-relative">
                <div class="header-title">
                    <h1>
                        <asp:Label ID="lblpagename" runat="server" Text="Label"></asp:Label>
                    </h1>
                </div>
                <div class="header-buttons">
                    <a class="sidebar-toggler" href="#">
                        <i class="fa fa-arrows-h"></i>
                    </a>
                    <a class="fullscreen" id="fullscreen-toggler" href="#">
                        <i class="fa fa-close"></i>
                    </a>
                </div>
            </div>
            <div class="page-body">
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
    
    

@Scripts.Render("~/bundles/myadminscript")
    

@RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            EditableTable.init();
            $("form").addClass("form-horizontal").attr("role", "form");
            $("#buttons * *").addClass("btn btn-primary");
            $('input[type="text"],input[type="datetime"],input[type="password"],textarea,select').addClass("form-control");
        });
    </script>
</body>
</html>