Tamin/Controllers/AdminPostGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamin.Models;
using System.IO;

namespace Tamin.Controllers
{
    [Authorize]

    public class AdminPostGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminPostGroups
        public ActionResult Index()

        {
            var postGroups = db.PostGroups.Include(p => p.Parent);

            return View(db.PostGroups.ToList());

        }



        public ActionResult Add()

        {
            ViewBag.ParentId = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle");
            return PartialView();

        }



        [HttpPost]

        public ActionResult Add([Bind(Include = "PostGroupID,ParentId,PostGroupTitle,ImageUrl")] PostGroup postGroup, HttpPostedFileBase ImageUrl)

        {

            if (ModelState.IsValid)

            {
                if (ImageUrl != null)
                {
                    var fileName = Path.GetFileName(ImageUrl.FileName);
                    string newFilename = Guid.NewGuid().ToString()
                                             .Replace("-", string.Empty) +
                                         Path.GetExtension(fileName);
                    newFilename = "/Uploads/PostGroups/" + newFilename;
                    var physicalPath = Server.MapPath(newFilename);
                    ImageUrl.SaveAs(physicalPath);
                    postGroup.ImageUrl = newFilename;
                }
                db.PostGroups.Add(postGroup);

                db.SaveChanges();

            }
            ViewBag.ParentId = new SelectList(db.PostGroups, "PostGroupID", "PostGroupTitle", postGroup.ParentId);
            return PartialView("_Detail", db.PostGroups.ToList());

        }



        public ActionResult Edit(int id)

        {

            return PartialView(db.PostGroups.Find(id));

        }



        [HttpPost]

        public ActionResult Edit(PostGroup model, int id)

        {

            if (ModelState.IsValid)

            {

                db.Entry(model).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();

            }

            return PartialView("_Detail", db.PostGroups.ToList());

        }



        public ActionResult Delete(int id)

        {

            db.PostGroups.Remove(db.PostGroups.Find(id));

            db.SaveChanges();

            return PartialView("_Detail", db.PostGroups.ToList());

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamin/Views/AdminPostGroups/Add.cshtml
@model Tamin.Models.PostGroup

@using (Ajax.BeginForm("Add", "AdminPostGroups", new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "div-record",
    OnSuccess = "$('.close').click()"
}, new { @id = "form_UploadFile", @enctype = "multipart/form-data" }))

{

    <div class="modal-body">

        <div class="row form-group">

            <div class="col-md-12">

                <div class="input-group">



                    @Html.TextBoxFor(m => m.PostGroupTitle, new { @class = "form-control", @placeholder = "عنوان گروه خبر" })

                </div>

            </div>

        </div>

        <div class="row form-group">

                <div class="col-md-12">

                    <div class="input-group">

                        <div class="form-group">

                            <div class="col-md-10">
                                @Html.DropDownList("ParentId", "-- والد گروه خبر را انتخاب کنید --")
                                @Html.ValidationMessageFor(model => model.ParentId)
                            </div>
                        </div>

                    </div>

                </div>

            </div>
        <br />

        <div class="row form-group">

            <div class="col-md-12">

                <div class="input-group">



                    @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-4 right" })
                    <br />
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ImageUrl)
                        @Html.ValidationMessageFor(model => model.ImageUrl)

                    </div>

                </div>

            </div>
        </div>


    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary" name="cmd"><i class="fa fa-check"></i>&nbsp;ذخیره</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;بستن</button>
    </div>

}

Tamin/Views/AdminPostGroups/Edit.cshtml
@model Tamin.Models.PostGroup

@using (Ajax.BeginForm("Edit", "AdminPostGroups", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }))

{

    @Html.HiddenFor(m => m.PostGroupId)

    <div class="modal-body">

        <div class="row form-group">

            <div class="col-md-12">

                <div class="input-group">

                    <span class="input-group-addon"><i class="fa fa-user-plus"></i></span>

                    @Html.TextBoxFor(m => m.PostGroupTitle, new { @class = "form-control", @placeholder = "Username" })

                </div>

            </div>

        </div>


        <br />

        <div class="row form-group">

            <div class="col-md-12">

                <div class="input-group">



                    @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-4 right" })
                    <br />
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ImageUrl)
                        @Html.ValidationMessageFor(model => model.ImageUrl)

                    </div>

                </div>

            </div>
        </div>

    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary" name="cmd"><i class="fa fa-check"></i>&nbsp;ذخیره</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;بستن</button>
    </div>

}

Tamin/Views/AdminPostGroups/Index.cshtml
@{

    ViewBag.Title = "Index";
    Layout = Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    //Layout = null;
}



<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />

<link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" />

<link href="@Url.Content("~/Content/font-awesome.min.css")" rel="stylesheet" />

<script src="@Url.Content("~/Scripts/jquery-2.1.1.min.js")"></script>

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>

<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>



<div id="main-div">

    <div class="clearfix">&nbsp;</div>

    <div class="clearfix">&nbsp;</div>

    <div class="container">

        <a href="@Url.Action("Add", "AdminPostGroups")" id="Add" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i>&nbsp;ایجاد گروه خبر</a>

        <div id="div-record">

            @Html.Partial("_Detail")

        </div>

    </div>





    <div class="modal fade" id="Add-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                    <h4 class="modal-title">گروه خبر</h4>

                </div>

                <div class="divForAdd">

                </div>

            </div>

        </div>

    </div>



    <div class="modal fade" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                    <h4 class="modal-title">بروز رسانی</h4>

                </div>

                <div class="divForUpdate">

                </div>

            </div>

        </div>

    </div>

</div>

Tamin/Views/AdminPostGroups/_Detail.cshtml
@model IList<Tamin.Models.PostGroup>
<div class="col-md-10 right" style="float: right;margin-top: 10px">
<div class="table-responsive">

    <table class="table table-bordered table-striped" >

        <thead>

        <tr>

            <th style="text-align: right">عنوان گروه خبر</th>

            <th style="text-align: right">تصویر</th>

            @*<th>State</th>

                <th>Country</th>*@

            <th></th>

            <th></th>

        </tr>

        </thead>

        <tbody>

        @foreach (var item in Model)

        {

            <tr>

                <td>

                    @Html.DisplayFor(modelItem => item.PostGroupTitle)

                </td>

                <td>

                    @if (!String.IsNullOrEmpty(@item.ImageUrl))
                    {
                        <img style="border-radius: 5px;" width="50" height="50" src="@Url.Content(@item.ImageUrl)" />
                    }

                </td>

                @*<td>

                        @Html.DisplayFor(modelItem => item.PostGroupTitle)

                    </td>

                    <td>

                        @Html.DisplayFor(modelItem => item.PostGroupTitle)

                    </td>*@

                <td>

                    <a href="@Url.Action("Edit", "AdminPostGroups", new { id = item.PostGroupId })" class="editDialog"><i class="fa fa-pencil-square-o"></i>&nbsp;ویرایش</a>

                </td>

                <td>

                    @Ajax.ActionLink("حذف", "Delete", "AdminPostGroups", new { @id = item.PostGroupId }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "div-record" }, new { @class = "fa fa-pencil-square-o" })

                </td>

            </tr>

        }

        </tbody>

    </table>

</div>
</div>
<script>

    $(document).ready(function () {

        $('#Add').click(function (event) {

            event.preventDefault();

            $.get(this.href, function (response) {

                $('.divForAdd').html(response);

            });

            $('#Add-Model').modal({

                backdrop: 'static',

            }, 'show');

        });

        $('.editDialog').click(function (event) {

            event.preventDefault();

            $.get(this.href, function (response) {

                $('.divForUpdate').html(response);

            });

            $('#Edit-Model').modal({

                backdrop: 'static',

            }, 'show');

        });

    });

</script>