Tamin/Controllers/AdminCommentsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Tamin.Models;

namespace Tamin.Controllers
{
    [Authorize]
    public class AdminCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminComments
        public async Task<ActionResult> Index()
        {
            //var comments = db.Comments.Include(c => c.Parent);

            var comments = db.Comments.Include(c => c.posts).Include(c => c.Parent);

            return View(await comments.ToListAsync());
        }

        // GET: AdminComments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: AdminComments/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            ViewBag.PageId = comment.PostID;
            ViewBag.ParentId = comment.Comment_ID;
            ViewBag.ParentContent = comment.CommentContent;
            ViewBag.Author = "مدیر سایت";
            ViewBag.AuthorEmail = "Admin@Test.com";
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View();
        }
        // POST: AdminComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Comment_ID,User_ID,PostID,Parent_ID,Comment_Date,CommentIsActive,Author,Comment_title,CommentContent,Author_Email,UserLogsData")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Parent_ID = new SelectList(db.Comments, "Comment_ID", "Author", comment.Parent_ID);
            return View(comment);
        }

        // GET: AdminComments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "PostID", "PostTitle", comment.PostID);
            ViewBag.Parent_ID = new SelectList(db.Comments, "Comment_ID", "Author", comment.Parent_ID);
            return View(comment);
        }

        // POST: AdminComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Comment_ID,User_ID,PostID,Parent_ID,Comment_Date,CommentIsActive,Author,Comment_title,CommentContent,Author_Email,UserLogsData")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PageID = new SelectList(db.Posts, "PostID", "PageTitle", comment.PostID);

            ViewBag.Parent_ID = new SelectList(db.Comments, "Comment_ID", "Author", comment.Parent_ID);
            return View(comment);
        }

        // GET: AdminComments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: AdminComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Comment comment = await db.Comments.FindAsync(id);
            db.Comments.Remove(comment);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamin/Views/AdminComments/Create.cshtml
@model Tamin.Models.Comment

@{
 ViewBag.Title = "افزودن ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="panel">
    <header class="panel-heading">افزودن
	</header>
    <div class="panel-body">
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
	@Html.ValidationSummary(true)
    @*@Html.Hidden("PostID")
    @Html.Hidden("Parent_ID")
    @Html.Hidden("Author")
    @Html.Hidden("Author_Email")*@
    <fieldset>    

        <div class="form-group">
            @Html.LabelFor(model => model.User_ID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_ID)
                @Html.ValidationMessageFor(model => model.User_ID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostID)
                @Html.ValidationMessageFor(model => model.PostID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parent_ID, "Parent_ID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Parent_ID", String.Empty)
                @Html.ValidationMessageFor(model => model.Parent_ID)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Comment_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment_Date)
                @Html.ValidationMessageFor(model => model.Comment_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentIsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentIsActive)
                @Html.ValidationMessageFor(model => model.CommentIsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author)
                @Html.ValidationMessageFor(model => model.Author)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment_title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment_title)
                @Html.ValidationMessageFor(model => model.Comment_title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentContent, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentContent)
                @Html.ValidationMessageFor(model => model.CommentContent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author_Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author_Email)
                @Html.ValidationMessageFor(model => model.Author_Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserLogsData, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserLogsData)
                @Html.ValidationMessageFor(model => model.UserLogsData)
            </div>
        </div>

        <div id="buttons">            
			<div class="col-md-2">
            </div>
            <div class="col-md-10">
			<input type="submit" class="btn btn-primary"  value="ثبت" />
            @Html.ActionLink("بازگشت به فهرست", "Index")						
			</div>
        </div>
        
        
        
        

        @*<div class="form-group">
            @Html.Label("دیدگاه کاربر", new { @class = "col-md-2 control-label", @disabled = "disabled" })
            <div class="col-md-10">
                @Html.TextArea("ParentContent", new { @disabled = "disabled" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Comment_Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment_Date)
                @Html.ValidationMessageFor(model => model.Comment_Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentIsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentIsActive)
                @Html.ValidationMessageFor(model => model.CommentIsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentContent, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CommentContent)
                @Html.ValidationMessageFor(model => model.CommentContent)
            </div>
        </div>
        <div id="buttons">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <input type="submit" class="btn btn-primary" value="ثبت" />
                @Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>*@

    </fieldset>

}
</div>
    </section>

Tamin/Views/AdminComments/Delete.cshtml
@model Tamin.Models.Comment

@{
    ViewBag.Title = "حذف ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="panel panel-danger">
    <header class="panel-heading">حذف
	</header>
    <div class="panel-body">

<h4>آیا مطمئن هستید که این مورد حذف شود؟</h4>
<fieldset>    
 @*<div class="display-label">
         @Html.DisplayNameFor(model => model.Parent.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Parent.Author)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.User_ID)
    </div>*@
    @*<div class="display-field">
        @Html.DisplayFor(model => model.User_ID)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.PostID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostID)
    </div>*@
 <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment_Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment_Date)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.CommentIsActive)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CommentIsActive)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment_title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment_title)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.CommentContent)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CommentContent)
    </div>
 <div class="display-label">
         @Html.DisplayNameFor(model => model.Author_Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author_Email)
    </div>
 @*<div class="display-label">
         @Html.DisplayNameFor(model => model.UserLogsData)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserLogsData)
    </div>*@
   </fieldset>
@using (Html.BeginForm()) {
@Html.AntiForgeryToken()
		<div id="buttons">            
			<div class="col-lg-2">
            </div>
            <div class="col-lg-10">
			<input type="submit" class="btn btn-primary"  value="حذف" />
            @Html.ActionLink("بازگشت به فهرست", "Index")						
			</div>
        </div>
}
</div>
</section>

Tamin/Views/AdminComments/Details.cshtml
@model Tamin.Models.Comment

@{
      ViewBag.Title = "جزئیات ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>جزئیات</h2>

<fieldset> 
  <div class="display-label">
         @Html.DisplayNameFor(model => model.Parent.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Parent.Author)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.User_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User_ID)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.PostID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostID)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment_Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment_Date)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.CommentIsActive)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CommentIsActive)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.Author)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment_title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment_title)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.CommentContent)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CommentContent)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.Author_Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Author_Email)
    </div>

  <div class="display-label">
         @Html.DisplayNameFor(model => model.UserLogsData)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserLogsData)
    </div>

</fieldset>
<p>
 @Html.ActionLink("ویرایش", "Edit", new { id=Model.Comment_ID }) |
    @Html.ActionLink("بازگشت به فهرست", "Index")
</p>

Tamin/Views/AdminComments/Edit.cshtml
@model Tamin.Models.Comment
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="widget">
    <div class="widget-header">
        <span class="widget-caption">ویرایش کامنت</span>
    </div>
    <div class="widget-body">
        <div class="row">
            @using (Html.BeginForm("Edit", "AdminComments", FormMethod.Post, new { @id = "form_UploadFile", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="col-md-12 padding-10">
                    <div class="form-group">
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    </div>
                </div>
               
                    <div class="col-md-12 padding-10">
                        @Html.HiddenFor(model => model.Comment_ID)

                        @if (Model.PostID != null)
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.PostID, "عنوان صفحه", new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("PostID", "--عنوان صفحه را انتخاب کنید--" )
                                    @Html.ValidationMessageFor(model => model.PostID)
                                </div>
                            </div>
                        }
                    </div>

                    <div class="col-md-12 padding-10">
                        @if (Model.Parent_ID != null)
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.Parent_ID, "والد نظر", new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Parent_ID", "--کامنت والد را انتخاب کنید--")
                                    @Html.ValidationMessageFor(model => model.Parent_ID)
                                </div>
                            </div>
                        }
                    </div>

                    <div class="col-md-12 padding-10">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Comment_Date, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Comment_Date, @*new { htmlAttributes =*@ new { @type = "text", @class = "form-control col-md-3", @id = "definput" @*}*@ })
                                @Html.ValidationMessageFor(model => model.Comment_Date)
                            </div>
                        </div>
                    </div>

                        <div class="col-md-12 padding-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CommentIsActive, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @*@Html.EditorFor(model => model.PostIsActive)*@
                                    @*<label class="pull-right">
                                        @Html.EditorFor(model => model.CommentIsActive, new { @class = "checkbox", @type = "checkbox" })
                                        <span class="text"></span>
                                    </label>*@
                                    <div class="col-xs-4">
                                        @Html.CheckBoxFor(model => model.CommentIsActive, new { @class = "checkbox-slider slider-icon colored-blue", @type = "checkbox" })
                                        <span class="text"></span>
                                    </div>
                                    @*@Html.ValidationMessageFor(model => model.CommentIsActive)*@

                                    @Html.CheckBoxFor(model => model.CommentIsActive)
                                    @Html.CheckBox("CommentIsActive", true)

                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 padding-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Author, new { @type = "text", @class = "form-control col-md-3", @id = "definput" })
                                    @Html.ValidationMessageFor(model => model.Author)
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 padding-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Comment_title, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Comment_title, new { @type = "text", @class = "form-control col-md-3", @id = "definput" })
                                    @Html.ValidationMessageFor(model => model.Comment_title)
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 padding-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Author_Email, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Author_Email, new { @type = "text", @class = "form-control col-md-3", @id = "definput" })
                                    @Html.ValidationMessageFor(model => model.Author_Email)
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 padding-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.CommentContent, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.CommentContent, new { @type = "text", @class = "form-control col-md-12", @id = "definput" })
                                    @Html.ValidationMessageFor(model => model.CommentContent)

                                </div>
                            </div>
                        </div>

                            <div id="buttons">
                                <div class="col-md-2">
                                </div>
                                <div class="col-md-10">
                                    <input type="submit" class="btn btn-primary" value="ثبت" />
                                    @Html.ActionLink("بازگشت به فهرست", "Index")
                                </div>
                            </div>





                            }
                        </div>
    </div>
</div>

Tamin/Views/AdminComments/Index.cshtml
@model IEnumerable<Tamin.Models.Comment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="panel">
    <header class="panel-heading">
        فهرست
        <span class="tools pull-left">
            <a class="fa fa-chevron-down" href="javascript:;"></a>
        </span>
    </header>
    <div class="panel-body">

        <div class="space15"></div>
        <table class="table editable-table table-hover table-bordered" id="editable-sample">
            <thead>
            <tr>

                <th>
                    @Html.DisplayName("نام فرستنده")                

                </th>
                <th>
                    @Html.DisplayName("تاریخ ارسال")                
                </th>
                <th>
                    @Html.DisplayName("وضعیت نمایش")
                </th>                
                <th>
                    @Html.DisplayName("عنوان نظر")
                </th>
                <th>
                    @Html.DisplayName("آدرس ایمیل")
                </th>
                <th>@Html.DisplayName("دستورات")</th>


               
            </tr>
            </thead>
            <tbody>
            @if (Model.Count() == 0)
            {
                <tr><td colspan="8" class="text-center">هیچ داده ای جهت نمایش وجود ندارد</td></tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr class="">


                        <td>
                            @Html.DisplayFor(modelItem => item.Author)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comment_Date)
                        </td>

                        <td>
                            @*@Html.DisplayFor(modelItem => item.CommentIsActive)
                            @if (item.CommentIsActive == true)
                            {
                                @:تایید
                            }
                            else
                            {
                                @:انتظار
                            }*@

                            <div class="col-xs-4">

                                @*<label class="pull-right">*@
                                @Html.CheckBoxFor(model => item.CommentIsActive, new { @class = "checkbox-slider slider-icon colored-blue", @type = "checkbox" })
                                <span class="text"></span>
                                @*</label>*@
                            </div>
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Comment_title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Author_Email)
                        </td>
                        <td>


                            @Html.ActionLink("مشاهده", "Edit", new { id = item.Comment_ID }, new { @class = "btn btn-primary btn-xs" })

                            @Html.ActionLink("حذف", "Delete", new { id = item.Comment_ID }, new { @class = "btn btn-danger btn-xs" })

                           
                               
                                    
                                   
                                      
                                       @Html.CheckBoxFor(modelItem => item.CommentIsActive)
                                        
                            
                        </td>
                    </tr>
                }
            }
                
            </tbody>
        </table>
    </div>
</section>